version: "3"

services:
  server:
    image: ${URL_SHORTENER_IMAGE:-url_shortener}
    container_name: url_shortener_server
    environment:
      SERVER_PORT: ${SERVER_PORT:-80}
      REDIRECT_SERVE_ENDPOINT: ${REDIRECT_SERVE_ENDPOINT:-http://localhost}
      MYSQL_SERVER_ADDR: ${MYSQL_SERVER_ADDR:-db:3306}
      MYSQL_SERVER_ROOT_PASSWORD: ${MYSQL_SERVER_ROOT_PASSWORD:-test_url_shortener}
      REDIS_SERVER_ADDR: ${REDIS_SERVER_ADDR:-cache:6379}
      REDIS_SERVER_ADMIN_PASSWORD: ${REDIS_SERVER_ADMIN_PASSWORD:-}
      CHECK_EXPIRATION_INTERVAL: ${CHECK_EXPIRATION_INTERVAL:-60}

    depends_on:
      - db
      - cache
    ports:
      - ${EXTERNAL_SERVER_PORT:-80}:${SERVER_PORT:-80}
    networks:
      - url_shortener_application

  cache:
    image: redis:6.2-alpine
    container_name: url_shortener_redis_cache
    networks:
      - url_shortener_application
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 10s
      retries: 10

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test_url_shortener
    container_name: url_shortener_mysql_db
    networks:
      - url_shortener_application
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - data-volume:/var/lib/mysql
    healthcheck:
      test: [ "CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 10s
      retries: 10

networks:
  url_shortener_application:
    driver: bridge

volumes:
  data-volume:
    external: false
