CREATE DATABASE IF NOT EXISTS url_shortener;

USE url_shortener;

CREATE TABLE IF NOT EXISTS short_urls
(
    id         INTEGER       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    url        VARCHAR(2083) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expire_at  TIMESTAMP     NOT NULL
);